# Tokyo Night bar colors
set $accent #7aa2f7
set $foreground #a9b1d6
set $background #1a1b26
set $indicator_color #ff9e64
set $tn_surface #3b3d57
set $tn_comment #565f89
set $transparent $transparent

bar {
        output primary

        tray_output none
        status_command i3blocks -c ~/.config/i3/i3blocks.conf
        separator_symbol " | "

        position top
        padding 0 2px
        font pango:JetBrains Mono Nerd Font 12
        workspace_min_width 32

        # Colors
        colors {
          background $background

          # <colorclass> <border> <background> <text>
          focused_workspace  $accent          $accent          $background
          active_workspace   $tn_surface      $tn_surface      $foreground
          inactive_workspace $background      $background      $tn_comment
          urgent_workspace   $indicator_color $indicator_color  $background
        }
}

bar {
        output nonprimary

        i3bar_command i3bar --transparency

        tray_output none
        position top
        padding 0 2px
        font pango:JetBrains Mono Nerd Font 12
        workspace_min_width 32

        # Colors
        colors {
          background $transparent

          # <colorclass> <border> <background> <text>
          focused_workspace  $accent          $accent          $background
          active_workspace   $tn_surface      $tn_surface      $foreground
          inactive_workspace $transparent        $transparent        $tn_comment
          urgent_workspace   $indicator_color $indicator_color  $background
        }
}

gaps inner 8px
