separator=false
separator_block_width=0
markup=pango

[kbmap]
command=out=$(~/.config/i3/scripts/blocks/kbmap); [ -n "$out" ] && echo "$out"
interval=once
signal=1

[radio_lofi]
command=out=$(~/.config/i3/scripts/blocks/radio_lofi); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=once
signal=4

[radio_sympa]
command=out=$(~/.config/i3/scripts/blocks/radio_sympa); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=once
signal=5

[wireguard]
command=out=$(~/.config/i3/scripts/blocks/wireguard); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=once
signal=2

[wifi]
command=out=$(~/.config/i3/scripts/blocks/wifi); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=10

[bluetooth]
command=out=$(~/.config/i3/scripts/blocks/bluetooth); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=10

[volume]
command=out=$(~/.config/i3/scripts/blocks/volume); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=once
signal=3

[battery]
command=out=$(~/.config/i3/scripts/blocks/battery); [ -n "$out" ] && echo " <span foreground='#888888'>|</span> $out"
interval=30

[time]
command=echo " <span foreground='#888888'>|</span> $(date '+%a %d %b  %H:%M ')"
interval=30
