# caps as compose key
exec --no-startup-id setxkbmap -layout fr -option compose:caps
exec --no-startup-id setxkbmap -layout us -option compose:caps

# toggle azerty/querty
# bindsym $mod+ exec --no-startup-id ~/.config/i3/scripts/toggle_kbmap.sh && $refresh_i3status
