# Tokyo Night
set $accent #7aa2f7
set $cursor #c0caf5
set $foreground #a9b1d6
set $background #1a1b26
set $selection_fg #c0caf5
set $selection_bg #7aa2f7

set $indicator_color #ff9e64
set $active_border_color #33ccff
set $inactive_border_color #595959

set $tn_surface #3b3d57
set $tn_comment #565f89

default_border pixel 4

gaps inner 6px
gaps outer 12px

# Force borders on Electron/GTK apps that use client-side decorations
for_window [class="discord"] border pixel 4
for_window [class="obsidian"] border pixel 4
for_window [class="Cursor"] border pixel 4

for_window [title="i3block-wlctl"] floating enable, resize set 1200 800, move position center
for_window [title="i3block-bluetui"] floating enable, resize set 1200 800, move position center


# class                 border                 backgr.       text          indicator child_border
client.focused          $active_border_color   $selection_bg $selection_bg $indicator_color $active_border_color
client.unfocused        $inactive_border_color $background   $foreground   $indicator_color $inactive_border_color
