# compositor
exec_always --no-startup-id picom --backend xrender &

# wallpaper
exec_always --no-startup-id feh --bg-fill ~/Pictures/background.jpg

# autorandr handles displays while docking/undocking laptop
exec --no-startup-id autorandr --change

# cursor size fix
exec --no-startup-id xsetroot -cursor_name left_ptr
exec --no-startup-id xrdb -merge ~/.Xresources
